<Project Sdk="Godot.NET.Sdk/4.7.2">

	<PropertyGroup>
		<AssemblyTitle>Estragonia HelloWorld Sample</AssemblyTitle>
		<TargetFramework>net10.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<AnalysisMode>Recommended</AnalysisMode>
		<IsPackable>false</IsPackable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<EnableDefaultAvaloniaItems>false</EnableDefaultAvaloniaItems>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<PackageReference PrivateAssets="all" />
	</ItemDefinitionGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/JLeb.Estragonia/JLeb.Estragonia.csproj" />
		<PackageReference Include="Semi.Avalonia" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="UI/*.png" />
		<AvaloniaResource Include="UI/Assets/**" />
		<None Include="**\*.axaml" />
		<Compile Update="**\*.axaml.cs">
			<DependentUpon>%(Filename)</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
