<Project Sdk="Godot.NET.Sdk/4.7.2">

	<PropertyGroup>
		<AssemblyTitle>Estragonia HelloWorld Sample</AssemblyTitle>
		<TargetFramework>net10.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<AnalysisMode>Recommended</AnalysisMode>
		<IsPackable>false</IsPackable>
		<EnableDefaultAvaloniaItems>false</EnableDefaultAvaloniaItems>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<PackageReference PrivateAssets="all" />
	</ItemDefinitionGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/JLeb.Estragonia/JLeb.Estragonia.csproj" />
		<ProjectReference Include="../HelloWorld.UI/HelloWorld.UI.csproj" />
	</ItemGroup>

</Project>
