<Project Sdk="Godot.NET.Sdk/4.7.2">

	<PropertyGroup>
		<AssemblyTitle>GodotGame</AssemblyTitle>
		<TargetFramework>net10.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<IsPackable>false</IsPackable>
		<EnableDefaultAvaloniaItems>false</EnableDefaultAvaloniaItems>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ouse.Estragonia" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../GodotGame.UI/GodotGame.UI.csproj" />
	</ItemGroup>

</Project>
